syntax = "proto3";

package com.tk75attractions.monitoring.v1;

enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  LOG_LEVEL_VERBOSE = 1;
  LOG_LEVEL_DEBUG = 2;
  LOG_LEVEL_INFO = 3;
  LOG_LEVEL_WARN = 4;
  LOG_LEVEL_ERROR = 5;
}

message SystemLog {
  message BatteryLog {
    uint32 battery_capacity = 1;
  }

  oneof data {
    BatteryLog battery = 1;
  }
}

message CrashLog {}

message LogPacket {
  LogLevel level = 1;
  int64 occured_at = 2;
  oneof body {
    string app = 3;
    SystemLog system = 4;
    CrashLog crash = 5;
  }
}
